<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About</h1>
    <nav>
        <ul>
            <?php
                foreach($routes as $route)
                {
            ?>
                    <li><a href=<?= $route['href']?>><?= $route['name']?></a></li>
            <?php
                }
            ?>
        </ul>
    </nav>
</body>
</html>