<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
    <h1>Home</h1>
    <nav>
        <ul>
            <?php
                foreach($routes as $route)
                {
            ?>
                    <li><a href=<?= $route['href']?>><?= $route['name']?></a></li>
            <?php
                }
            ?>
        </ul>
    </nav>
    <form action="index.php" method="GET">
        <label for="route">Route</label>
        <select name="route" id="route">
            <option value="about">About</option>
            <option value="contact">Contact</option>
        </select>
        <button type="submit">Envoyer</button>
    </form>
</body>
</html>